"""Added columns

Revision ID: ecd2368e1c15
Revises: 8c0767e2514f
Create Date: 2020-09-22 12:28:34.595440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ecd2368e1c15'
down_revision = '8c0767e2514f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitchtype', sa.String(), nullable=True))
    op.drop_column('pitches', 'date_posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('date_posted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('pitches', 'pitchtype')
    # ### end Alembic commands ###
